[Settings]
;Toggle Compass break notification
bShowCompassNotif = true
;Toggle Compass damage
bEnableCompassDamage = true
;Durability value every damaged map adds to the total
iDamagedMapDurability = 10
;Durability value every new map adds to the total
iMapDurability = 20
;Bypass the check for a map in your inventory
bBypassMapCheck = false
;Bypass the check for a compass in your inventory
bBypassCompassCheck = false
;toggle damage for compass
bEnableCompassDamage = true
;how many (ingame)days does one compass last
fCompassDurationDays = 3.0

[DebugLogging]
bEnableDebugLog = true

[Texts]
;Message to show when you try to open the map without a may in your inventory
sMessageText = You need a map to see your location!
;Message to show when the compass breaks
sCompassBreakMessage = Your compass can not guide you anymore...
